---
- hosts: all
  vars:
    packages:
      - vim
      - wget
      - curl
      - gnupg
      - htop
      - software-properties-common
      - git
      - zsh
      - zsh-syntax-highlighting
      - apt-transport-https 
      - lsb-release 
      - ca-certificates
      - mcrypt
      - rsync

    user: leonidas
    domain: piwik.test

  roles:
    - init
    - role: nginx
      become: yes
    - role: php
      become: yes
    - role: mysql
      become: yes
    - certbot
...