- hosts: all
  vars:
    packages:
      - vim
      - wget
      - curl
      - htop
      - git
      - zsh
  tasks:
    - name: Ensure a list of packages installed
      become: 'yes'
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
        install_recommends: no
    - name: All done!
      debug:
        msg: Packages have been successfully installed
    - name: Check if .zshrc exists
      stat:
        path: ~/.zshrc
      register: stat_rc_result
    - name: Check if .oh-my-zsh exists
      stat:
        path: ~/.oh-my-zsh
      register: stat_oh_my_zsh_result
    - name: Installation de Oh! MY ZSH
      shell:
        cmd: yes | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when: not stat_oh_my_zsh_result.stat.exists
    - name: change user shell to zsh
      become: 'yes'
      user:
        name: vagrant
        shell: /bin/zsh
